### ISSUE TITLE
Clang warning because ImGuiButtonFlags is defined twice

### ISSUE THREAD

**Issue by floooh** [cimgui/cimgui#166]
After updating from 1.77 to 1.79 I'm seeing the following warning in Xcode:

```
...cimgui/cimgui.h:201:13: warning: redefinition of typedef 'ImGuiButtonFlags' is a C11 feature [-Wtypedef-redefinition]
typedef int ImGuiButtonFlags;
            ^
...cimgui/cimgui.h:143:13: note: previous definition is here
typedef int ImGuiButtonFlags;
```

First definition is here:

https://github.com/cimgui/cimgui/blob/ee5534d7cd709e4ad0944e41f9c47d9ed59bd85e/cimgui.h#L143

Second is here:

https://github.com/cimgui/cimgui/blob/ee5534d7cd709e4ad0944e41f9c47d9ed59bd85e/cimgui.h#L201

I guess the reason is that ImGui now has this typedef in two different headers:

First in imgui_internal.h here:

https://github.com/ocornut/imgui/blob/71cc636696bd17c81514da49707e909958c14632/imgui_internal.h#L120

...and again in imgui.h here:

https://github.com/ocornut/imgui/blob/71cc636696bd17c81514da49707e909958c14632/imgui.h#L159

In ImGui 1.77, only imgui_internal.h had this definition, but not in imgui.h:

https://github.com/ocornut/imgui/blob/9418dcb69355558f70de260483424412c5ca2fce/imgui_internal.h#L115

(cc @ocornut, maybe this is an oversight in the original ImGui headers? It looks like ImGuiButtonFlags was originally a private type, but is now part of the public API, so it was added to imgui.h, but not removed from imgui_internal.h?)

**Comment by ocornut** [comment]
> (cc @ocornut, maybe this is an oversight in the original ImGui headers? 

Correct. I have now pushed a fix in imgui/master. Thanks for the heads up !

**Comment by sonoro1234** [comment]
It will be incorporated when binding to 1.80
