### ISSUE TITLE
Unable to compile on windows using Visual Studio 16.8.5 2019

### ISSUE THREAD

**Issue by RUSshy** [cimgui/cimgui#182]
I made sure i followed the readme, i even tried to clone the whole repo + submodules again, but no luck

No specific instructions on the readme..

<details>
  <summary>Log</summary>

```log

Build started...
1>------ Build started: Project: cimgui, Configuration: Release x64 ------
1>cimgui.cpp
1>C:\tmp\cimgui\cimgui.h(251,24): error C2990: 'ImVector': non-class template has already been declared as a class template
1>C:\tmp\cimgui\./imgui/imgui.h(1625): message : see declaration of 'ImVector'
1>C:\tmp\cimgui\cimgui.h(296,1): error C2011: 'ImVec2': 'struct' type redefinition
1>C:\tmp\cimgui\cimgui.h(91): message : see declaration of 'ImVec2'
1>C:\tmp\cimgui\cimgui.h(300,1): error C2011: 'ImVec4': 'struct' type redefinition
1>C:\tmp\cimgui\cimgui.h(90): message : see declaration of 'ImVec4'
1>C:\tmp\cimgui\cimgui.h(304,5): error C2365: 'ImGuiWindowFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(889): message : see declaration of 'ImGuiWindowFlags_None'
1>C:\tmp\cimgui\cimgui.h(305,5): error C2365: 'ImGuiWindowFlags_NoTitleBar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(890): message : see declaration of 'ImGuiWindowFlags_NoTitleBar'
1>C:\tmp\cimgui\cimgui.h(306,5): error C2365: 'ImGuiWindowFlags_NoResize': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(891): message : see declaration of 'ImGuiWindowFlags_NoResize'
1>C:\tmp\cimgui\cimgui.h(307,5): error C2365: 'ImGuiWindowFlags_NoMove': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(892): message : see declaration of 'ImGuiWindowFlags_NoMove'
1>C:\tmp\cimgui\cimgui.h(308,5): error C2365: 'ImGuiWindowFlags_NoScrollbar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(893): message : see declaration of 'ImGuiWindowFlags_NoScrollbar'
1>C:\tmp\cimgui\cimgui.h(309,5): error C2365: 'ImGuiWindowFlags_NoScrollWithMouse': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(894): message : see declaration of 'ImGuiWindowFlags_NoScrollWithMouse'
1>C:\tmp\cimgui\cimgui.h(310,5): error C2365: 'ImGuiWindowFlags_NoCollapse': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(895): message : see declaration of 'ImGuiWindowFlags_NoCollapse'
1>C:\tmp\cimgui\cimgui.h(311,5): error C2365: 'ImGuiWindowFlags_AlwaysAutoResize': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(896): message : see declaration of 'ImGuiWindowFlags_AlwaysAutoResize'
1>C:\tmp\cimgui\cimgui.h(312,5): error C2365: 'ImGuiWindowFlags_NoBackground': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(897): message : see declaration of 'ImGuiWindowFlags_NoBackground'
1>C:\tmp\cimgui\cimgui.h(313,5): error C2365: 'ImGuiWindowFlags_NoSavedSettings': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(898): message : see declaration of 'ImGuiWindowFlags_NoSavedSettings'
1>C:\tmp\cimgui\cimgui.h(314,5): error C2365: 'ImGuiWindowFlags_NoMouseInputs': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(899): message : see declaration of 'ImGuiWindowFlags_NoMouseInputs'
1>C:\tmp\cimgui\cimgui.h(315,5): error C2365: 'ImGuiWindowFlags_MenuBar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(900): message : see declaration of 'ImGuiWindowFlags_MenuBar'
1>C:\tmp\cimgui\cimgui.h(316,5): error C2365: 'ImGuiWindowFlags_HorizontalScrollbar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(901): message : see declaration of 'ImGuiWindowFlags_HorizontalScrollbar'
1>C:\tmp\cimgui\cimgui.h(317,5): error C2365: 'ImGuiWindowFlags_NoFocusOnAppearing': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(902): message : see declaration of 'ImGuiWindowFlags_NoFocusOnAppearing'
1>C:\tmp\cimgui\cimgui.h(318,5): error C2365: 'ImGuiWindowFlags_NoBringToFrontOnFocus': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(903): message : see declaration of 'ImGuiWindowFlags_NoBringToFrontOnFocus'
1>C:\tmp\cimgui\cimgui.h(319,5): error C2365: 'ImGuiWindowFlags_AlwaysVerticalScrollbar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(904): message : see declaration of 'ImGuiWindowFlags_AlwaysVerticalScrollbar'
1>C:\tmp\cimgui\cimgui.h(320,5): error C2365: 'ImGuiWindowFlags_AlwaysHorizontalScrollbar': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(905): message : see declaration of 'ImGuiWindowFlags_AlwaysHorizontalScrollbar'
1>C:\tmp\cimgui\cimgui.h(321,5): error C2365: 'ImGuiWindowFlags_AlwaysUseWindowPadding': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(906): message : see declaration of 'ImGuiWindowFlags_AlwaysUseWindowPadding'
1>C:\tmp\cimgui\cimgui.h(322,5): error C2365: 'ImGuiWindowFlags_NoNavInputs': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(907): message : see declaration of 'ImGuiWindowFlags_NoNavInputs'
1>C:\tmp\cimgui\cimgui.h(323,5): error C2365: 'ImGuiWindowFlags_NoNavFocus': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(908): message : see declaration of 'ImGuiWindowFlags_NoNavFocus'
1>C:\tmp\cimgui\cimgui.h(324,5): error C2365: 'ImGuiWindowFlags_UnsavedDocument': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(909): message : see declaration of 'ImGuiWindowFlags_UnsavedDocument'
1>C:\tmp\cimgui\cimgui.h(325,5): error C2365: 'ImGuiWindowFlags_NoNav': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(910): message : see declaration of 'ImGuiWindowFlags_NoNav'
1>C:\tmp\cimgui\cimgui.h(326,5): error C2365: 'ImGuiWindowFlags_NoDecoration': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(911): message : see declaration of 'ImGuiWindowFlags_NoDecoration'
1>C:\tmp\cimgui\cimgui.h(327,5): error C2365: 'ImGuiWindowFlags_NoInputs': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(912): message : see declaration of 'ImGuiWindowFlags_NoInputs'
1>C:\tmp\cimgui\cimgui.h(328,5): error C2365: 'ImGuiWindowFlags_NavFlattened': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(915): message : see declaration of 'ImGuiWindowFlags_NavFlattened'
1>C:\tmp\cimgui\cimgui.h(329,5): error C2365: 'ImGuiWindowFlags_ChildWindow': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(916): message : see declaration of 'ImGuiWindowFlags_ChildWindow'
1>C:\tmp\cimgui\cimgui.h(330,5): error C2365: 'ImGuiWindowFlags_Tooltip': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(917): message : see declaration of 'ImGuiWindowFlags_Tooltip'
1>C:\tmp\cimgui\cimgui.h(331,5): error C2365: 'ImGuiWindowFlags_Popup': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(918): message : see declaration of 'ImGuiWindowFlags_Popup'
1>C:\tmp\cimgui\cimgui.h(332,5): error C2365: 'ImGuiWindowFlags_Modal': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(919): message : see declaration of 'ImGuiWindowFlags_Modal'
1>C:\tmp\cimgui\cimgui.h(333,5): error C2365: 'ImGuiWindowFlags_ChildMenu': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(920): message : see declaration of 'ImGuiWindowFlags_ChildMenu'
1>C:\tmp\cimgui\cimgui.h(334,2): error C2371: 'ImGuiWindowFlags_': redefinition; different basic types
1>C:\tmp\cimgui\./imgui/imgui.h(887): message : see declaration of 'ImGuiWindowFlags_'
1>C:\tmp\cimgui\cimgui.h(336,5): error C2365: 'ImGuiInputTextFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(929): message : see declaration of 'ImGuiInputTextFlags_None'
1>C:\tmp\cimgui\cimgui.h(337,5): error C2365: 'ImGuiInputTextFlags_CharsDecimal': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(930): message : see declaration of 'ImGuiInputTextFlags_CharsDecimal'
1>C:\tmp\cimgui\cimgui.h(338,5): error C2365: 'ImGuiInputTextFlags_CharsHexadecimal': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(931): message : see declaration of 'ImGuiInputTextFlags_CharsHexadecimal'
1>C:\tmp\cimgui\cimgui.h(339,5): error C2365: 'ImGuiInputTextFlags_CharsUppercase': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(932): message : see declaration of 'ImGuiInputTextFlags_CharsUppercase'
1>C:\tmp\cimgui\cimgui.h(340,5): error C2365: 'ImGuiInputTextFlags_CharsNoBlank': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(933): message : see declaration of 'ImGuiInputTextFlags_CharsNoBlank'
1>C:\tmp\cimgui\cimgui.h(341,5): error C2365: 'ImGuiInputTextFlags_AutoSelectAll': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(934): message : see declaration of 'ImGuiInputTextFlags_AutoSelectAll'
1>C:\tmp\cimgui\cimgui.h(342,5): error C2365: 'ImGuiInputTextFlags_EnterReturnsTrue': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(935): message : see declaration of 'ImGuiInputTextFlags_EnterReturnsTrue'
1>C:\tmp\cimgui\cimgui.h(343,5): error C2365: 'ImGuiInputTextFlags_CallbackCompletion': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(936): message : see declaration of 'ImGuiInputTextFlags_CallbackCompletion'
1>C:\tmp\cimgui\cimgui.h(344,5): error C2365: 'ImGuiInputTextFlags_CallbackHistory': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(937): message : see declaration of 'ImGuiInputTextFlags_CallbackHistory'
1>C:\tmp\cimgui\cimgui.h(345,5): error C2365: 'ImGuiInputTextFlags_CallbackAlways': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(938): message : see declaration of 'ImGuiInputTextFlags_CallbackAlways'
1>C:\tmp\cimgui\cimgui.h(346,5): error C2365: 'ImGuiInputTextFlags_CallbackCharFilter': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(939): message : see declaration of 'ImGuiInputTextFlags_CallbackCharFilter'
1>C:\tmp\cimgui\cimgui.h(347,5): error C2365: 'ImGuiInputTextFlags_AllowTabInput': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(940): message : see declaration of 'ImGuiInputTextFlags_AllowTabInput'
1>C:\tmp\cimgui\cimgui.h(348,5): error C2365: 'ImGuiInputTextFlags_CtrlEnterForNewLine': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(941): message : see declaration of 'ImGuiInputTextFlags_CtrlEnterForNewLine'
1>C:\tmp\cimgui\cimgui.h(349,5): error C2365: 'ImGuiInputTextFlags_NoHorizontalScroll': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(942): message : see declaration of 'ImGuiInputTextFlags_NoHorizontalScroll'
1>C:\tmp\cimgui\cimgui.h(350,5): error C2365: 'ImGuiInputTextFlags_AlwaysInsertMode': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(943): message : see declaration of 'ImGuiInputTextFlags_AlwaysInsertMode'
1>C:\tmp\cimgui\cimgui.h(351,5): error C2365: 'ImGuiInputTextFlags_ReadOnly': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(944): message : see declaration of 'ImGuiInputTextFlags_ReadOnly'
1>C:\tmp\cimgui\cimgui.h(352,5): error C2365: 'ImGuiInputTextFlags_Password': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(945): message : see declaration of 'ImGuiInputTextFlags_Password'
1>C:\tmp\cimgui\cimgui.h(353,5): error C2365: 'ImGuiInputTextFlags_NoUndoRedo': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(946): message : see declaration of 'ImGuiInputTextFlags_NoUndoRedo'
1>C:\tmp\cimgui\cimgui.h(354,5): error C2365: 'ImGuiInputTextFlags_CharsScientific': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(947): message : see declaration of 'ImGuiInputTextFlags_CharsScientific'
1>C:\tmp\cimgui\cimgui.h(355,5): error C2365: 'ImGuiInputTextFlags_CallbackResize': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(948): message : see declaration of 'ImGuiInputTextFlags_CallbackResize'
1>C:\tmp\cimgui\cimgui.h(356,5): error C2365: 'ImGuiInputTextFlags_CallbackEdit': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(949): message : see declaration of 'ImGuiInputTextFlags_CallbackEdit'
1>C:\tmp\cimgui\cimgui.h(357,5): error C2365: 'ImGuiInputTextFlags_Multiline': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(951): message : see declaration of 'ImGuiInputTextFlags_Multiline'
1>C:\tmp\cimgui\cimgui.h(358,5): error C2365: 'ImGuiInputTextFlags_NoMarkEdited': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(952): message : see declaration of 'ImGuiInputTextFlags_NoMarkEdited'
1>C:\tmp\cimgui\cimgui.h(359,2): error C2371: 'ImGuiInputTextFlags_': redefinition; different basic types
1>C:\tmp\cimgui\./imgui/imgui.h(927): message : see declaration of 'ImGuiInputTextFlags_'
1>C:\tmp\cimgui\cimgui.h(361,5): error C2365: 'ImGuiTreeNodeFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(958): message : see declaration of 'ImGuiTreeNodeFlags_None'
1>C:\tmp\cimgui\cimgui.h(362,5): error C2365: 'ImGuiTreeNodeFlags_Selected': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(959): message : see declaration of 'ImGuiTreeNodeFlags_Selected'
1>C:\tmp\cimgui\cimgui.h(363,5): error C2365: 'ImGuiTreeNodeFlags_Framed': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(960): message : see declaration of 'ImGuiTreeNodeFlags_Framed'
1>C:\tmp\cimgui\cimgui.h(364,5): error C2365: 'ImGuiTreeNodeFlags_AllowItemOverlap': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(961): message : see declaration of 'ImGuiTreeNodeFlags_AllowItemOverlap'
1>C:\tmp\cimgui\cimgui.h(365,5): error C2365: 'ImGuiTreeNodeFlags_NoTreePushOnOpen': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(962): message : see declaration of 'ImGuiTreeNodeFlags_NoTreePushOnOpen'
1>C:\tmp\cimgui\cimgui.h(366,5): error C2365: 'ImGuiTreeNodeFlags_NoAutoOpenOnLog': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(963): message : see declaration of 'ImGuiTreeNodeFlags_NoAutoOpenOnLog'
1>C:\tmp\cimgui\cimgui.h(367,5): error C2365: 'ImGuiTreeNodeFlags_DefaultOpen': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(964): message : see declaration of 'ImGuiTreeNodeFlags_DefaultOpen'
1>C:\tmp\cimgui\cimgui.h(368,5): error C2365: 'ImGuiTreeNodeFlags_OpenOnDoubleClick': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(965): message : see declaration of 'ImGuiTreeNodeFlags_OpenOnDoubleClick'
1>C:\tmp\cimgui\cimgui.h(369,5): error C2365: 'ImGuiTreeNodeFlags_OpenOnArrow': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(966): message : see declaration of 'ImGuiTreeNodeFlags_OpenOnArrow'
1>C:\tmp\cimgui\cimgui.h(370,5): error C2365: 'ImGuiTreeNodeFlags_Leaf': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(967): message : see declaration of 'ImGuiTreeNodeFlags_Leaf'
1>C:\tmp\cimgui\cimgui.h(371,5): error C2365: 'ImGuiTreeNodeFlags_Bullet': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(968): message : see declaration of 'ImGuiTreeNodeFlags_Bullet'
1>C:\tmp\cimgui\cimgui.h(372,5): error C2365: 'ImGuiTreeNodeFlags_FramePadding': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(969): message : see declaration of 'ImGuiTreeNodeFlags_FramePadding'
1>C:\tmp\cimgui\cimgui.h(373,5): error C2365: 'ImGuiTreeNodeFlags_SpanAvailWidth': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(970): message : see declaration of 'ImGuiTreeNodeFlags_SpanAvailWidth'
1>C:\tmp\cimgui\cimgui.h(374,5): error C2365: 'ImGuiTreeNodeFlags_SpanFullWidth': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(971): message : see declaration of 'ImGuiTreeNodeFlags_SpanFullWidth'
1>C:\tmp\cimgui\cimgui.h(375,5): error C2365: 'ImGuiTreeNodeFlags_NavLeftJumpsBackHere': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(972): message : see declaration of 'ImGuiTreeNodeFlags_NavLeftJumpsBackHere'
1>C:\tmp\cimgui\cimgui.h(376,5): error C2365: 'ImGuiTreeNodeFlags_CollapsingHeader': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(974): message : see declaration of 'ImGuiTreeNodeFlags_CollapsingHeader'
1>C:\tmp\cimgui\cimgui.h(377,2): error C2371: 'ImGuiTreeNodeFlags_': redefinition; different basic types
1>C:\tmp\cimgui\./imgui/imgui.h(956): message : see declaration of 'ImGuiTreeNodeFlags_'
1>C:\tmp\cimgui\cimgui.h(379,5): error C2365: 'ImGuiPopupFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(987): message : see declaration of 'ImGuiPopupFlags_None'
1>C:\tmp\cimgui\cimgui.h(380,5): error C2365: 'ImGuiPopupFlags_MouseButtonLeft': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(988): message : see declaration of 'ImGuiPopupFlags_MouseButtonLeft'
1>C:\tmp\cimgui\cimgui.h(381,5): error C2365: 'ImGuiPopupFlags_MouseButtonRight': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(989): message : see declaration of 'ImGuiPopupFlags_MouseButtonRight'
1>C:\tmp\cimgui\cimgui.h(382,5): error C2365: 'ImGuiPopupFlags_MouseButtonMiddle': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(990): message : see declaration of 'ImGuiPopupFlags_MouseButtonMiddle'
1>C:\tmp\cimgui\cimgui.h(383,5): error C2365: 'ImGuiPopupFlags_MouseButtonMask_': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(991): message : see declaration of 'ImGuiPopupFlags_MouseButtonMask_'
1>C:\tmp\cimgui\cimgui.h(384,5): error C2365: 'ImGuiPopupFlags_MouseButtonDefault_': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(992): message : see declaration of 'ImGuiPopupFlags_MouseButtonDefault_'
1>C:\tmp\cimgui\cimgui.h(385,5): error C2365: 'ImGuiPopupFlags_NoOpenOverExistingPopup': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(993): message : see declaration of 'ImGuiPopupFlags_NoOpenOverExistingPopup'
1>C:\tmp\cimgui\cimgui.h(386,5): error C2365: 'ImGuiPopupFlags_NoOpenOverItems': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(994): message : see declaration of 'ImGuiPopupFlags_NoOpenOverItems'
1>C:\tmp\cimgui\cimgui.h(387,5): error C2365: 'ImGuiPopupFlags_AnyPopupId': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(995): message : see declaration of 'ImGuiPopupFlags_AnyPopupId'
1>C:\tmp\cimgui\cimgui.h(388,5): error C2365: 'ImGuiPopupFlags_AnyPopupLevel': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(996): message : see declaration of 'ImGuiPopupFlags_AnyPopupLevel'
1>C:\tmp\cimgui\cimgui.h(389,5): error C2365: 'ImGuiPopupFlags_AnyPopup': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(997): message : see declaration of 'ImGuiPopupFlags_AnyPopup'
1>C:\tmp\cimgui\cimgui.h(390,2): error C2371: 'ImGuiPopupFlags_': redefinition; different basic types
1>C:\tmp\cimgui\./imgui/imgui.h(985): message : see declaration of 'ImGuiPopupFlags_'
1>C:\tmp\cimgui\cimgui.h(392,5): error C2365: 'ImGuiSelectableFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1003): message : see declaration of 'ImGuiSelectableFlags_None'
1>C:\tmp\cimgui\cimgui.h(393,5): error C2365: 'ImGuiSelectableFlags_DontClosePopups': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1004): message : see declaration of 'ImGuiSelectableFlags_DontClosePopups'
1>C:\tmp\cimgui\cimgui.h(394,5): error C2365: 'ImGuiSelectableFlags_SpanAllColumns': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1005): message : see declaration of 'ImGuiSelectableFlags_SpanAllColumns'
1>C:\tmp\cimgui\cimgui.h(395,5): error C2365: 'ImGuiSelectableFlags_AllowDoubleClick': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1006): message : see declaration of 'ImGuiSelectableFlags_AllowDoubleClick'
1>C:\tmp\cimgui\cimgui.h(396,5): error C2365: 'ImGuiSelectableFlags_Disabled': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1007): message : see declaration of 'ImGuiSelectableFlags_Disabled'
1>C:\tmp\cimgui\cimgui.h(397,5): error C2365: 'ImGuiSelectableFlags_AllowItemOverlap': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1008): message : see declaration of 'ImGuiSelectableFlags_AllowItemOverlap'
1>C:\tmp\cimgui\cimgui.h(398,2): error C2371: 'ImGuiSelectableFlags_': redefinition; different basic types
1>C:\tmp\cimgui\./imgui/imgui.h(1001): message : see declaration of 'ImGuiSelectableFlags_'
1>C:\tmp\cimgui\cimgui.h(400,5): error C2365: 'ImGuiComboFlags_None': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1014): message : see declaration of 'ImGuiComboFlags_None'
1>C:\tmp\cimgui\cimgui.h(401,5): error C2365: 'ImGuiComboFlags_PopupAlignLeft': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1015): message : see declaration of 'ImGuiComboFlags_PopupAlignLeft'
1>C:\tmp\cimgui\cimgui.h(402,5): error C2365: 'ImGuiComboFlags_HeightSmall': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1016): message : see declaration of 'ImGuiComboFlags_HeightSmall'
1>C:\tmp\cimgui\cimgui.h(403,5): error C2365: 'ImGuiComboFlags_HeightRegular': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1017): message : see declaration of 'ImGuiComboFlags_HeightRegular'
1>C:\tmp\cimgui\cimgui.h(404,5): error C2365: 'ImGuiComboFlags_HeightLarge': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1018): message : see declaration of 'ImGuiComboFlags_HeightLarge'
1>C:\tmp\cimgui\cimgui.h(405,5): error C2365: 'ImGuiComboFlags_HeightLargest': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1019): message : see declaration of 'ImGuiComboFlags_HeightLargest'
1>C:\tmp\cimgui\cimgui.h(406,5): error C2365: 'ImGuiComboFlags_NoArrowButton': redefinition; previous definition was 'enumerator'
1>C:\tmp\cimgui\./imgui/imgui.h(1020): message : see declaration of 'ImGuiComboFlags_NoArrowButton'
1>C:\tmp\cimgui\cimgui.h(406,43): fatal error C1003: error count exceeds 100; stopping compilation
1>Done building project "cimgui.vcxproj" -- FAILED.
2>------ Build started: Project: ALL_BUILD, Configuration: Release x64 ------
2>Building Custom Rule C:/tmp/cimgui/CMakeLists.txt
3>------ Skipped Build: Project: INSTALL, Configuration: Release x64 ------
3>Project not selected to build for this solution configuration 
========== Build: 1 succeeded, 1 failed, 1 up-to-date, 1 skipped ==========

```

</details>

**Comment by RUSshy** [comment]
A reboot solved the issue
